//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossyRoad_View.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossyRoad_View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Crossy Road.
        /// </summary>
        public static string Game_Name {
            get {
                return ResourceManager.GetString("Game.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра окончена.
        /// </summary>
        public static string GameOver_GameOver {
            get {
                return ResourceManager.GetString("GameOver.GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый рекорд!.
        /// </summary>
        public static string GameOver_Highscore {
            get {
                return ResourceManager.GetString("GameOver.Highscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя:.
        /// </summary>
        public static string GameOver_Highscore_EnterName {
            get {
                return ResourceManager.GetString("GameOver.Highscore.EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя не должно быть пустым или состоять из пробельных символов!.
        /// </summary>
        public static string GameOver_Highscore_InvalidName {
            get {
                return ResourceManager.GetString("GameOver.Highscore.InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очки: .
        /// </summary>
        public static string GameOver_Score {
            get {
                return ResourceManager.GetString("GameOver.Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на перемещение игрока - ↑/↓/→/←, выход из игры - Esc.
        /// </summary>
        public static string HelpText_Game {
            get {
                return ResourceManager.GetString("HelpText.Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на завершение ввода имени - Enter, возврат в меню - Esc.
        /// </summary>
        public static string HelpText_GameOver_Highscore {
            get {
                return ResourceManager.GetString("HelpText.GameOver.Highscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на навигация - ↑/↓, выбор пункта меню - Enter.
        /// </summary>
        public static string HelpText_Menu {
            get {
                return ResourceManager.GetString("HelpText.Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на возврат в меню - Esc.
        /// </summary>
        public static string HelpText_ToMenu {
            get {
                return ResourceManager.GetString("HelpText.ToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя игрока.
        /// </summary>
        public static string Highscores_Column_Player {
            get {
                return ResourceManager.GetString("Highscores.Column.Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Набранные очки.
        /// </summary>
        public static string Highscores_Column_Score {
            get {
                return ResourceManager.GetString("Highscores.Column.Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица рекордов.
        /// </summary>
        public static string Highscores_Title {
            get {
                return ResourceManager.GetString("Highscores.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как играть?.
        /// </summary>
        public static string Information_Title {
            get {
                return ResourceManager.GetString("Information.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CROSSY ROAD.
        /// </summary>
        public static string Menu_GameName {
            get {
                return ResourceManager.GetString("Menu.GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главное меню.
        /// </summary>
        public static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu.Title", resourceCulture);
            }
        }
    }
}
